### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by andriycraft** [BlueBirdMC/BlueBird#33]
![image](https://user-images.githubusercontent.com/92477814/190700266-7b4ed632-20c2-446b-a8d1-87052d078dc6.png)

**Comment by andriycraft** [comment]
idk why this happens

**Comment by VaxPex** [comment]
ip leaks

**Comment by andriycraft** [comment]
no

**Comment by andriycraft** [comment]
most parts of ips are blurred
